# Generated by Django 5.0.1 on 2024-02-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("users", "0002_remove_shopprofile_alternative_no_customuser_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopMenu",
            fields=[
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.shopprofile",
                    ),
                ),
                ("products", models.ManyToManyField(to="products.product")),
            ],
        ),
    ]
