# Generated by Django 5.0.1 on 2024-02-04 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_shopmenu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopMenu",
        ),
    ]
