version: 0.1

# environment_variables:
  # plaintext:
  #   DJANGO_SETTINGS_MODULE: config.settings.test
  #   SECRET_KEY: nosecret
  #   DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
  #   DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
  #   STREAM_INCOMING_PRIVATE_KEY: changeme
  #   STREAM_INCOMING_PUBLIC_KEY: changeme
  #   GOOGLE_API_KEY: changeme
  #   OPBEAT_ENABLED: False
  #ALLOWED_HOSTS = '127.0.0.1 localhost 65.0.101.213'
#DATABASE_URL = "postgres://campusdelivery_django_user:VzYI4zb3aPiKLlUPglvvDgdlp4nE5qzB@dpg-cm9oiu21hbls73ba1t6g-a.singapore-postgres.render.com/campusdelivery_django"
#DEBUG = True
#SECRET_KEY = "django-insecure-sy1hrm4zb_gu^%b+t=g+0-&$bnhity-yh#i&ivcvhi-tncrl2z"
env:
  parameter-store:
    ALLOWED_HOSTS: "ALLOWED_HOSTS"
    DATABASE_URL: "DATABASE_URL"
    DEBUG: "DEBUG"
    SECRET_KEY: "SECRET_KEY"
phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
