version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/docker/web/Dockerfile.prod
    volumes:
      - static:/app/web/static

    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - AWS_SES_FROM_EMAIL=${AWS_SES_FROM_EMAIL}
      - AWS_SES_ACCESS_KEY_ID=${AWS_SES_ACCESS_KEY_ID}
      - AWS_SES_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
      - DOMAIN=${DOMAIN}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - AUTH_COOKIE_SECURE=${AUTH_COOKIE_SECURE}
      - REDIRECT_URLS=${REDIRECT_URLS}
      - GOOGLE_AUTH_KEY=${GOOGLE_AUTH_KEY}
      - GOOGLE_AUTH_SECRET_KEY=${GOOGLE_AUTH_SECRET_KEY}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}

  www:
    container_name: www
    build:
      context: .
      dockerfile: apps/docker/www/Dockerfile.prod
      args:
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
      - NEXT_PUBLIC_REDIRECT_URL=${NEXT_PUBLIC_REDIRECT_URL}
      
    volumes:
      - node_modules:/app/www/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    volumes:
      - static:/app/web/static
      - ./certbot/www/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
    entrypoint: ["certbot"]
    command: certonly --webroot --webroot-path=/var/www/certbot --non-interactive --email gupta.rishabh.abcd@gmail.com -d cciitbhilai.shop --agree-tos --no-eff-email
             
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    depends_on:
      - nginx
volumes:
  static:
  node_modules:
   