version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/web/staticfiles
      #- ./app/:/usr/src/app/
      #- static_volume:/home/app/web/staticfiles
      #- media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  
  frontend:
    build: ./frontend
    volumes:
      - react_build:/usr/src/frontend/build/
  nginx:
    image: nginx:latest
    ports:
      - 80:8001
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static
      - react_build:/var/www/frontend
    depends_on:
      - web
      - frontend

  
volumes:
  static:
  postgres_data:
  react_build:
  
