version: '3.8'

services:
  backend:
    volumes:
      - static:/static
    build:
      context: ./backend
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:    
    
    

