version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/docker/web/Dockerfile
    volumes:
      - static:/app/web/static

    ports:
      - 8000:8000
    env_file:
      - ./apps/web/.env


  www:
    container_name: www
    build:
      context: .
      dockerfile: apps/docker/www/Dockerfile
    env_file:
      - ./apps/www/.env.local
    volumes:
      - node_modules:/app/www/node_modules

    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    volumes:
      - static:/app/web/static
      - ./certbot/www/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --non-interactive --email gupta.rishabh.abcd@gmail.com -d cciitbhilai.shop --agree-tos --no-eff-email
             
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw

volumes:
  static:
  node_modules: