# Generated by Django 5.0.1 on 2024-02-16 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_shopprofile_alternative_no_customuser_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shopprofile",
            name="user",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
