FROM node:alpine

# CMD [ "mkdir", "/app/www/" ]
WORKDIR /app/www
COPY ./apps/www/ .



ARG NEXT_PUBLIC_HOST
RUN echo $NEXT_PUBLIC_HOST 
RUN echo $NEXT_PUBLIC_REDIRECT_URL 
ENV NEXT_PUBLIC_HOST $NEXT_PUBLIC_HOST
ENV NEXT_PUBLIC_REDIRECT_URL $NEXT_PUBLIC_REDIRECT_URL





RUN npm install
RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]

